version: "3.9"

services:
  db:
    image: postgres:15
    container_name: medpulse_db
    restart: always
    environment:
      POSTGRES_USER: medpulse_user
      POSTGRES_PASSWORD: bodemurairi2
      POSTGRES_DB: medpulse_db
    ports:
      - "5433:5432"  # host port 5433 maps to container 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./api
    container_name: medpulse_backend
    restart: always
    env_file:
      - ./api/.env
    environment:
      POSTGRES_USER: medpulse_user
      POSTGRES_PASSWORD: bodemurairi2
      POSTGRES_DB: medpulse_db
      DATABASE_URL: postgresql+psycopg2://medpulse_user:bodemurairi2@db/medpulse_db
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ["./wait-for-db.sh", "db", "uvicorn", "web.web:app", "--host", "0.0.0.0", "--port", "8080"]

  frontend:
    build:
      context: ./Frontend-summative-MedPulse-main
    container_name: medpulse_frontend
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
